# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f634587560a50420fadf9afcb71c04549673b316acbbdc4cf2825f010d38bfc1b830c441b407657a2b68f069ad3c3202cade9ffa9f746d042157b7fadce3a5b9

test:
  secret_key_base: 7fe3a11a64102061b39756111b45390bb173b436568b3eb8e2201bda3d1b9e602b5e902c52b0edaefa725f12a78e3d14ef9a11f506d82cdf6ffc78c71c54e72f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
